---
version: '3.7'
services:
  app:
    build: proj
    volumes:
      - /data:/app42/App42/target/ 

  prod:      
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - /data:/usr/local/tomcat/webapps/
    depends_on:
      - app
      - bd

  bd:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "8001:8514"  
    volumes:
      - ./mysql:/var/lib/mysql    