---
version: '3.7'
services:
  build:
    build: build
    volumes:
      - /data:/app42/App42/target/ 

  prod:      
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - /data:/usr/local/tomcat/webapps/
    depends_on:
      - build

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1423
    ports:
      - "8001:8514"  
    volumes:
      - ./mysql:/var/lib/mysql    