---
version: '3.7'
services:
  build:
    build: build
    volumes:
      - /data:/tmp/calculator-servlet-example/target/ 

  prod:      
    build: prod
    ports:
      - "8080:8080"
    volumes:
      - /data:/usr/local/tomcat/webapps/
    depends_on:
      - build